name: Sync from Gitee
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Gitee Repo
        run: git clone https://gitee.com/kallonr/mu-music.git
      - name: Push to GitHub
        run: |
          cd mu-music
          git remote add github https://${{ secrets.GITHUB_TOKEN }}@github.com/kallonr/mu-music.git
          git push github main
